### ISSUE TITLE
can't signin on my deploys

### ISSUE THREAD

**Issue by AlliedToasters** [wgmi-rambo/nft-website#12]
not sure what the diff is but when i build and deploy, signin doesn't work :/ do i need to provide an infura token/uri somewhere?

**Comment by wgmi-rambo** [comment]
Just deployed to https://wgmi-nft-preview.netlify.app/ and I can sign in.

**Comment by wgmi-rambo** [comment]
If u have some test eth give it a try please since I have none for gas haha. Where u getting urs?
