### ISSUE TITLE
Test on Rinkeby Deploy

### ISSUE THREAD

**Issue by AlliedToasters** [wgmi-rambo/nft-website#9]
I deployed the contract to rinkeby - the test_deploy branch includes the abi and contract in the respective js files. Want to make sure I can connect a wallet on rinkeby and mint via the web interface.

**Comment by wgmi-rambo** [comment]
Ok will redeploy in 11ish hours

**Comment by wgmi-rambo** [comment]
deployed

**Comment by AlliedToasters** [comment]
I get "Please switch to Ethereum Mainnet" then "Wallet Connected" but "Minting Failed" when i try to mint

**Comment by wgmi-rambo** [comment]
Ah, we need to add and ‘else if’ clause for the rinkeby chain id in this block: https://github.com/wgmi-rambo/nft-website/blob/84ea2eb222f93c5692aba863756af8f9b1980e56/src/js/main.js#L117

**Comment by AlliedToasters** [comment]
I think [pr-11](https://github.com/wgmi-rambo/nft-website/pull/11) will should sort this.
